
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      cache:
        directories:
          - .
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make clean euboea
    - language: c
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make clean test
    - language: c
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - make clean coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: c
      addons:
        apt:
          packages:
            - gcc-multilib
            - lua50
      script:
        - make clean all
        - cd benchmarks && for i in {1..10}; do /bin/sh benchmark; done
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  cache: apt
